### ISSUE TITLE
determine folder structure for shared code

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/FHBig#4]
We will want this as stable as possible, as users will likely want to reference paths to executables.  To keep the main directory clean, I recommend creating one or two main folders then we branch out by topic and tools.  Suggestions?

**Comment by vortexing** [comment]
I would make a suggestion that we use the master branch as the repo to contain these paths, etc with a directory structure we decide on, BUT manage the actual website out of the gh-pages branch.  I can make that adjustment in the repo with a quick edit if people are fine with that.  @TapscottLab is that ok?  

The other issue I see is whether everyone can push to the master branch.  Perhaps we should require pull requests (make the master branch restricted), require a review from the community before they are merged.  Then perhaps we can start learning an appropriate structure for this as pull requests are merged and we find conflicts between things.  

I have no idea up front any particular structure to propose b/c I feel like the content and usage is/will be an evolving thing.  

If you all would like me to edit the repo to reflect these suggestions so you can envision the future structure, let me know.

**Comment by LisaMc** [comment]
Yes! I like the idea of separating the gh-pages and also requiring approved pull requests to the master branch.  

The folder structure will surely change over time, just trying to plan ahead to minimize the potential for a massive reorg. Hopefully we can decide upon a couple major themes/topics at the root level so it doesn't get bloated with individual projects

**Comment by chaochaowong** [comment]
I think it is better to separate the gh-pages repos and other projects and folders. What changes should be made to make it possible? I am not an expert of GitHub. Do we create another repos (i.e., https://github.com/FredHutch/FHBigProject) for project other than the gh-pages or create folders and branches under github.com/FredHutch/FHBig?

**Comment by jennylsmith** [comment]
Hi, I apologize for the late reply. I definitely agree that we should keep the master branch clean, with only a few subdirectories, as well as keeping that gh-pages as a separate branch and still require pull requests.  I'd like to start posting to the gh-pages branch, and since were in consensus about that structure, perhaps I could meet with @LisaMc sometime this week to discuss? I wanted to add 1) updated hours to the page to include the bioinformatics office hours, perhaps add information about the data science affinity group, biostats affinity group and 2) a quickstart for the rhino/gizmos (for new hires etc).  Also, what should we post to the gh-wiki versus the gh-pages? in fact, maybe #2 quickstart should be on the wiki?

**Comment by vortexing** [comment]
@TapscottLab I created the gh-pages branch.  I can adjust and test the website feed from this branch if I were an admin for this repo.  I also can make things the way I suggested and let you all see it rather than trying to explain it.  Then if you like it, we can just leave it and I can add instructions for use and contributions to the website in the readme.

**Comment by chaochaowong** [comment]
It is a great idea to add a quickstart for rhino/gizmos. I remembered when I started I had not idea about rhino and gizmos and SciComp.  It would be nice for new hires so that they don't waste time on figuring things out. The hours page totally needs update.

**Comment by vortexing** [comment]
Can someone review my pull request so that we can get the repo structure set up so that we can start on some of these other issues?
